### ISSUE TITLE
Octopus.using treats symbols and strings inconsistently

### ISSUE THREAD

**Issue by patbl** [thiagopradi/octopus#436] opened 2017-06-01 02:29 UTC
If you pass a valid shard name as a symbol, Octopus sends the query to the replica:

```ruby
Octopus.using(:valid_shard_name) do
  User.last
end
```

If you pass a string that doesn't match a shard, Octopus raises an exception (`RuntimeError: Nonexistent Shard Name: shard_that_does_not_exist`:

```ruby
Octopus.using("shard_that_does_not_exist") do
  User.last
end
```

If you pass a string that matches a shard, Octopus sends the query to the master.

```ruby
Octopus.using("valid_shard_name") do
  User.last
end
```

I didn't know that `Octopus.using` expected a symbol. I was passing it a string and things seemed to work. I didn't notice the problem till the app I work on started having performance problems, and even then it took me a few days to track down the problem.

I think that one of these two behaviors would be more consistent and less error-prone:

1. Raise an exception if the argument is a string.
2. Convert the argument to a symbol.

**Comment by thiagopradi** [comment] 2017-06-06 03:21
@patbl - thanks for the report. IMHO, both strings and symbols should have the same behavior. I'll try to update this behavior on the code, but feel free to send an patch. Thanks!

**Comment by thiagopradi** [comment] 2017-06-06 03:33
@patbl - after a few minutes of debugging, I couldn't reproduce your problem with strings (it works normally here). Can you provide more details about your setup?

**Comment by patbl** [comment] 2017-06-09 20:20
You're right, it looks like the issue is caused by one of our monkey patches. Thanks!

**Comment by patbl** [comment] 2017-06-09 20:25
I don't fully understand the issue, but the cause seems to be that we were adding the symbol but not the string to `allowed_shards`. Adding both fixes the issue, though I don't know yet whether that's the best solution.

**Comment by patbl** [comment] 2017-06-09 20:32
I wonder whether the shard names should be converted to either symbols or strings somewhere. For example,
 [here](https://github.com/thiagopradi/octopus/blob/15c15efa827b45db17e3a3de440722d32f090238/lib/octopus/model.rb#L135):

```ruby
def allowed_shard?(shard)
  if custom_octopus_connection
    allowed_shards && shard && allowed_shards.include?(shard) # maybe this should be `shard.to_sym`
  else
    true
  end
end
```

and [here](https://github.com/thiagopradi/octopus/blob/15c15efa827b45db17e3a3de440722d32f090238/lib/octopus/model.rb#L85)

```ruby
def allow_shard(*shards)
  self.allowed_shards ||= []
  self.allowed_shards += shards # maybe this should be `shards.map(&:to_sym)`
end
```

But I've only glanced at the code, so I don't know whether these changes would be safe or a good idea.

I'll reopen this, but feel free to close it if this is problem best handled on our end.

**Comment by yn-academia** [comment] 2017-06-12 21:23
The key is that we are using `allow_shard(symbol)` but are then doing `Octopus.using(string)` when using it.

**Comment by thiagopradi** [comment] 2017-11-04 18:22
https://github.com/thiagopradi/octopus/pull/439 has fixed the problem. 

Closing this issue.

Thiago

**Closed** 2017-11-04 18:22 UTC
